package cn;
// Generated 2019-4-22 19:53:13 by Hibernate Tools 5.4.2.Final

/**
 * Accumvistor generated by hbm2java
 */
public class Accumvistor implements java.io.Serializable {

	private Integer sum;

	public Accumvistor() {
	}

	public Accumvistor(int sum) {
		this.sum = sum;
	}

	public Integer getSum() {
		return this.sum;
	}

	public void setSum(int sum) {
		this.sum = sum;
	}

}
