package cn;
// Generated 2019-4-22 19:53:13 by Hibernate Tools 5.4.2.Final

/**
 * Comments generated by hbm2java
 */
public class Comments implements java.io.Serializable {

	private Integer id;
	private String shoeid;
	private String username;
	private String message;
	private String date;

	public Comments() {
	}

	public Comments(String shoeid, String username, String message, String date) {
		this.shoeid = shoeid;
		this.username = username;
		this.message = message;
		this.date = date;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getShoeid() {
		return this.shoeid;
	}

	public void setShoeid(String shoeid) {
		this.shoeid = shoeid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

}
