package cn;
// Generated 2019-4-22 19:53:13 by Hibernate Tools 5.4.2.Final

/**
 * Shoes generated by hbm2java
 */
public class Shoes  implements java.io.Serializable {

	@Override
	public String toString() {
		return "Shoes [shoeId=" + shoeId + ", brand=" + brand + ", size=" + size + ", kind=" + kind + ", sex=" + sex
				+ ", src=" + src + ", price=" + price + "]";
	}

	private String shoeId;
	private String brand;
	private Float size;
	private String kind;
	private String sex;
	private String src;
	private Float price;

	public Shoes() {
	}

	public Shoes(String shoeId, String brand, float size, String kind, String sex, String src, float price) {
		this.shoeId = shoeId;
		this.brand = brand;
		this.size = size;
		this.kind = kind;
		this.sex = sex;
		this.src = src;
		this.price = price;
	}

	public String getShoeId() {
		return this.shoeId;
	}

	public void setShoeId(String shoeId) {
		this.shoeId = shoeId;
	}

	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public Float getSize() {
		return this.size;
	}

	public void setSize(float size) {
		this.size = size;
	}

	public String getKind() {
		return this.kind;
	}

	public void setKind(String kind) {
		this.kind = kind;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getSrc() {
		return this.src;
	}

	public void setSrc(String src) {
		this.src = src;
	}

	public Float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

}
