<%@ page language="java" pageEncoding="utf-8" %>
<script type="text/javascript" src="JS/plugins/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="JS/plugins/bootstrap/dist/js/bootstrap.min.js"></script>
<script type="text/javascript" src="JS/plugins/jquery-bar-rating/dist/jquery.barrating.min.js"></script>
<script type="text/javascript" src="JS/plugins/owl-carousel/owl.carousel.min.js"></script>
<script type="text/javascript" src="JS/plugins/gmap3.min.js"></script>
<script type="text/javascript" src="JS/plugins/imagesloaded.pkgd.js"></script>
<script type="text/javascript" src="JS/plugins/isotope.pkgd.min.js"></script>
<script type="text/javascript" src="JS/plugins/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
<script type="text/javascript" src="JS/plugins/jquery.matchHeight-min.js"></script>
<script type="text/javascript" src="JS/plugins/slick/slick/slick.min.js"></script>
<script type="text/javascript" src="JS/plugins/elevatezoom/jquery.elevatezoom.js"></script>
<script type="text/javascript" src="JS/plugins/Magnific-Popup/dist/jquery.magnific-popup.min.js"></script>
<script type="text/javascript" src="JS/plugins/jquery-ui/jquery-ui.min.js"></script>
 <script type="text/javascript" src="http://ditu.google.cn/maps/api/js?key=AIzaSyAx39JFH5nhxze1ZydH-Kl8xXM3OK4fvcg&amp;region=GB"></script>
<script type="text/javascript" src="JS/plugins/revolution/js/jquery.themepunch.tools.min.js"></script>
<script type="text/javascript" src="JS/plugins/revolution/js/jquery.themepunch.revolution.min.js"></script>
<script type="text/javascript" src="JS/plugins/revolution/js/extensions/revolution.extension.video.min.js"></script>
<script type="text/javascript" src="JS/plugins/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
<script type="text/javascript" src="JS/plugins/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
<script type="text/javascript" src="JS/plugins/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
<script type="text/javascript" src="JS/plugins/revolution/js/extensions/revolution.extension.parallax.min.js"></script>
<script type="text/javascript" src="JS/plugins/revolution/js/extensions/revolution.extension.actions.min.js"></script>
<script type="text/javascript" src="JS/plugins/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>
<script type="text/javascript" src="JS/plugins/revolution/js/extensions/revolution.extension.migration.min.js"></script>
<!-- Custom scripts-->
<script type="text/javascript" src="JS/main.js"></script>