package com.shoes.entity;
// Generated 2019-4-22 19:53:13 by Hibernate Tools 5.4.2.Final

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private String orderid=null;
	private String userid=null;
	private String shoeid=null;
	private Integer num=null;
	private Float sumpric=null;
	private String date=null;
	private String subject=null;



	public String getSubject() {
		return subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Override
 	public String toString() {
		return "Orders [orderid=" + orderid + ", userid=" + userid + ", shoeid=" + shoeid + ", num=" + num
				+ ", sumpric=" + sumpric + ", date=" + date + "]";
	}

	public Orders() {
	}

	public Orders(String orderid, String userid, String shoeid, int num, float sumpric) {
		this.orderid = orderid;
		this.userid = userid;
		this.shoeid = shoeid;
		this.num = num;
		this.sumpric = sumpric;
	}

	public Orders(String orderid, String userid, String shoeid, int num, float sumpric, String date) {
		this.orderid = orderid;
		this.userid = userid;
		this.shoeid = shoeid;
		this.num = num;
		this.sumpric = sumpric;
		this.date = date;
	}

	public String getOrderid() {
		return this.orderid;
	}

	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getShoeid() {
		return this.shoeid;
	}

	public void setShoeid(String shoeid) {
		this.shoeid = shoeid;
	}

	public Integer getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	public Float getSumpric() {
		return this.sumpric;
	}

	public void setSumpric(Float sumpric) {
		this.sumpric = sumpric;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

}
